---
title: "Why do you have to wait more for the buses?"
author: "Kapil Khanal"
date: 2018-07-23T21:13:14-05:00
categories: ["R"]
tags: ["Applied Statistics", "Probability", "paradoxes"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# R Markdown

Inspection Paradox

Buses and trains are supposed to arrive at constant intervals, but in practice some intervals are longer than others. This means the buses do not follow schedule exactly. There is always some randomness..With your luck, you might think you are more likely to arrive during a long interval. It turns out you are right: a random arrival is more likely to fall in a long interval because, well, it’s longer..!

*Let's think of a scenario...*

Suppose a Bus service in your city says they pass a station every 10 minutes. This means you will assume that when you go to station randomly you would think that the average time is 5 minutes but




This is one case where the perspective of the individual and the group differs. For example, when you are waiting for the bus, there is high chance that you will be waiting longer than the average and also there will be time when you are right on time  


