---
title: "Watershed Quality in Minnesota"
author: "Kapil Khanal"
date: 2018-06-23T21:13:14-05:00
categories: ["Python","dplyr","ggplot2"]
tags: ["Statistics", "Data Cleaning", "WaterQuality"]
---

** Data Product Below... **
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Link of the Competition the data is of :  http://minneanalytics.org/minnemudac-2016/data/
Our Submission as a freshmen : 
<B> MINNEMUDAC:2016 </B> <br>
<I>Water Quality Analytics Competiton:</I> <br>
A blog on Data Analytics Competition that we recently participated . We were Ranked 5th out of 19th team that participated from regional universities of Midwest USA
This is the Analysis Report of a Analytics Competition that i participated in Minnesota on Nov 4 and Nov 5 in Eden Praire, Optum Technologies. This Competition was Organized by Minneanalytics[biggest analytics Group in Minneapolis], MUDAC[ Yearly analytics event of Winonat State University] and Social Data Science[a Data Science for Social Good Platform based in Minneapolis]

 Thanks to my Wonderful team  for collaboration and Professor for Helping this happen !
For interactive Dashboard of our Report:
https://public.tableau.com/profile/malek.hakim#!/vizhome/PARCELS_Story/WaterQualityVisualizationsintheTwinCities


*My first Data Analytics competition and we got honourable mention * 

 
This project is divided into two parts. 
<li> Data Cleaning and Data Management<br>
<li> Data Product and Presentation 

First Part of this project was done in Python. This is the link of the code: 
https://github.com/KapilKhanal/DSCI430/blob/master/project_data_khanal.py



The Data was sponsored by MinneMUDAC as part of the Fall Data Challenge

The second part of the project was focused on the making a usable data product. 
The  link of the code: https://github.com/KapilKhanal/DSCI430/blob/master/app.R

*Below you can use this product*
<iframe width="800" height="1000" scrolling="no" frameborder="yes"  src="https://kapilkhanal.shinyapps.io/r_final_app/"> </iframe>

