---
title: "Police  Data Challenge"
author: "Kapil Khanal"
date: 2017-07-23T21:13:14-05:00
categories: ["Python"]
tags: ["Applied Statistics", "Probability", "Information Games"]
---



# Police Data Challenge: Winner Recommendations
February 1, 2018

The Police Data Challenge contest brought talented high school and undergraduate students across the nation to show their passion for the good statistics can do.

With the Police Foundation’s efforts to make the information available, the 70 teams used real crime data sets from Baltimore, Seattle and Cincinnati police departments to analyze the best possible solutions for safer communities.

Check out below how the winning teams analyzed the best way to fight crime through statistics:

Winona State University, Winona, MN
Jimmy Hickey, Kapil Khanal, Luke Peacock divided the crimes into more detailed categories than what the Seattle Police Department data provided. They used the crime types and locations to discover that gun related crimes are condensed in specific areas. Their recommendation was to raise public awareness of the times and locations of high crimes and include more police for patrol.

Sponsored by: Silas Bergen 

Link to Presentation: https://thisisstatistics.org/wp-content/uploads/2018/01/Best-Overall-College-.pptx

Please visit here for code 
https://github.com/KapilKhanal/Police-Data-Challenge