---
title: "Truck Factor"
author: "Kapil Khanal"
date: 2019-07-23T21:13:14-05:00
categories: ["Python"]
tags: ["Software Engineering", "Data Product", "Project management"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Truck Factor

Today I learned an interesting concept in software engineering and project management called "Truck Factor". The minimum numbers of contributors of a project that needs to be hit by a truck before the project is crippled and unfinished.

my first thought was why would you think of such a extreme example.Seems like there is an emphasis on how important some people are to the project.This suggests a need for many heroes than a single hero. Its a good metric to see how centralized your project is in terms of contributions. You would want to many people on the project, helping each other so that if one gets hit by a bus, projects is not in serious trouble. 

There is a whole science of organizing project called Agile methodology if any one is interested.